### ISSUE TITLE
Automate cloud functions deployment

### ISSUE THREAD

**Issue by marvinmarnold** [eye-on-surveillance/sawt#45]
## Notes
There are three servers:
- NextJS frontend: Vercel, autodeployments working
- Postgres DB for saving queries: Supabase, autodeployments not necessary yet
- Endpoint for LLM computation: Google Cloud Functions, autodeployment [removed](https://github.com/eye-on-surveillance/the-great-inquirer/commit/1cb9ecb0f83d8efc8ffc3a803b80dadddc475735#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L29) because wasn't working

Only the cloud functions are in scope. Additional notes:
- There are a bunch of unused functions. Those were for tests and can be ignored.
- Currently using 4GB of memory for deployments, eg:

```
gcloud functions deploy getanswer \
    --gen2 \
    --runtime=python310 \
    --memory=4GB \
    --region=us-east1 \
    --source=packages/googlecloud/functions/getanswer \
    --entry-point=getanswer \
    --trigger-http \
    --allow-unauthenticated \
    --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
```
- Not sure why deployments were failing before. One known issue is adding [unnecessary quotes to OPENAI_API_KEY](https://github.com/openai/openai-python/issues/464#issuecomment-1593751169
). Typically failed deployments manifest with CORS errors when the web client attempts to invoke the function.
- `OPENAI_API_KEY` env var is already stored in GIthub.

## Acceptance criteria
- Deploys to `getanswer` when PR merged into `prod` branch.
- `prod` branch created. Write protections added to Github to prevent direct pushes.
- Deploys to `getanswer-staging` when PR merged into `main` branch.
- Bonus: Anything easy we can do to have a custom ephemeral function for each PR? In another project we are using git hashes, but it requires a nontrivial amount of code.

**Comment by nikkag** [comment]
Reactivated the workflow for staging: On a push to `main`, the code will deploy to `getanswer-staging`
https://github.com/eye-on-surveillance/the-great-inquirer/commit/3974df964faff467ab5e351848b1f7754c3f1c95

**Comment by nikkag** [comment]
[Build failed](https://github.com/eye-on-surveillance/the-great-inquirer/actions/runs/5491196443/jobs/10007492393)
Will investigate more later on to see what went wrong. For now I redeployed the staging function using the zip.

**Comment by nikkag** [comment]
Moving cache files out of the repo and using `dvc` to manage them seems to have fixed the issue!
* PR #48 for updating staging workflow + adding production workflow.
* `prod` branch has been created and [protections added](https://github.com/eye-on-surveillance/the-great-inquirer/settings/branch_protection_rules/39508959).

Will give ephemeral functions for PRs more thought.

**Comment by marvinmarnold** [comment]
Awesome. I'm not 100% sure but I think those large files will perpetually cause bloat in git history and increase the download size to clone. Created an [issue](https://github.com/eye-on-surveillance/the-great-inquirer/issues/49) to deal with that eventually.
